import 'dart:async';
import 'dart:math';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_auth/firebase_auth.dart' as firebase_auth;
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:Ratedly/resources/auth_methods.dart';
import 'package:Ratedly/responsive/mobile_screen_layout.dart';
import 'package:Ratedly/responsive/responsive_layout.dart';
import 'package:Ratedly/utils/utils.dart';
import 'package:Ratedly/widgets/text_filed_input.dart';
import 'package:Ratedly/services/analytics_service.dart'; // ✅ screen tracking
import 'package:Ratedly/services/debug_logger.dart'; // NEW
import 'package:Ratedly/services/device_session.dart'; // NEW

class ProfileSetupScreen extends StatefulWidget {
  final DateTime dateOfBirth;
  final VoidCallback onComplete;

  const ProfileSetupScreen({
    Key? key,
    required this.dateOfBirth,
    required this.onComplete,
  }) : super(key: key);

  @override
  State<ProfileSetupScreen> createState() => _ProfileSetupScreenState();
}

// Fix #2: only lets a-z, 0-9, ., _ ever land in the field — no reject-and-flash-red
// for a keystroke the user hasn't finished typing. Uppercase is silently
// lowercased instead of rejected, matching Instagram/TikTok behavior.
class _UsernameFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(
    TextEditingValue oldValue,
    TextEditingValue newValue,
  ) {
    final lowered = newValue.text.toLowerCase();
    final filtered = lowered.replaceAll(RegExp(r'[^a-z0-9_.]'), '');
    if (filtered == newValue.text) return newValue;

    final delta = newValue.text.length - filtered.length;
    final newOffset = (newValue.selection.end - delta).clamp(0, filtered.length);
    return TextEditingValue(
      text: filtered,
      selection: TextSelection.collapsed(offset: newOffset),
    );
  }
}

class _ProfileSetupScreenState extends State<ProfileSetupScreen>
    with WidgetsBindingObserver {
  static const _draftKeyPrefix = 'profile_setup_draft_v1';

  final TextEditingController _usernameController = TextEditingController();
  // NEW: needed so we can select-all the auto-generated username when the
  // field gains focus.
  final FocusNode _usernameFocusNode = FocusNode();

  bool _isLoading = false;
  String? _selectedGender;
  String? _usernameError;
  int _usernameLength = 0;
  bool _submitAttempted = false;
  bool _draftRestored = false;

  // NEW: tracks whether the current username text is still the untouched
  // auto-generated suggestion (vs. something the user actually typed or
  // edited). Drives the select-all-on-focus behavior below. Compared by
  // content (not by call ordering) against _autoGeneratedUsername, so it's
  // robust regardless of exactly when TextEditingController notifies its
  // listeners.
  bool _usernameIsAutoGenerated = false;
  String? _autoGeneratedUsername;

  // Added "Prefer not to say" so gender isn't a forced binary choice — no
  // "Custom" free-text option (product decision), just an explicit opt-out.
  // Any selected value here (including this one) flows through
  // _isFormValid/completeProfile/draft save-restore unchanged — nothing
  // else in this file special-cases "Male"/"Female" specifically.
  final List<String> _genders = ['Male', 'Female', 'Prefer not to say'];

  // NEW: word lists for a "cool but not gibberish" auto-generated username.
  // Kept short enough that adjective+noun+2-digit-number always stays well
  // under the 20-char max, and uses only lowercase letters/digits, so the
  // result always passes _validateUsernameText with no error.
  static const List<String> _usernameAdjectives = [
    'cosmic', 'silver', 'crimson', 'electric', 'velvet', 'golden', 'arctic',
    'neon', 'wild', 'lunar', 'solar', 'amber', 'shadow', 'crystal', 'turbo',
    'mellow', 'rapid', 'stellar', 'frosty', 'sunny',
  ];
  static const List<String> _usernameNouns = [
    'falcon', 'tiger', 'wolf', 'comet', 'phoenix', 'otter', 'raven', 'fox',
    'panther', 'eagle', 'dragon', 'wave', 'storm', 'ember', 'lynx', 'hawk',
    'panda', 'orca', 'viper', 'wren',
  ];
  static final Random _usernameRand = Random();

  String _generateUsername() {
    final adjective =
        _usernameAdjectives[_usernameRand.nextInt(_usernameAdjectives.length)];
    final noun = _usernameNouns[_usernameRand.nextInt(_usernameNouns.length)];
    final number = _usernameRand.nextInt(90) + 10; // two digits, 10-99
    final candidate = '$adjective$noun$number';
    // Safety net in case the word lists are ever edited to longer words.
    return candidate.length > 20 ? candidate.substring(0, 20) : candidate;
  }

  Future<String> _usernameAutogenKey() async =>
      '${_draftKeyPrefix}_username_autogen_${await DeviceSession.id}';

  @override
  void initState() {
    super.initState();
    AnalyticsService.screenEnter('profile_setup');
    WidgetsBinding.instance.addObserver(this); // Fix #5: catch backgrounding

    // Fix #2: debounce structural validation instead of validating on every
    // keystroke. Character-set enforcement now happens via the formatter, so
    // this listener only checks shape rules (length, consecutive punctuation)
    // and does so after a short pause in typing — the error text under the
    // field only appears once the user stops typing for 800ms, not on every
    // keystroke.
    _usernameController.addListener(_onUsernameChanged);

    // NEW: select the whole auto-generated username on focus, so the user
    // can just start typing over it instead of manually clearing it first.
    _usernameFocusNode.addListener(_handleUsernameFocusChange);

    _restoreDraft(); // Fix #5 (+ NEW: applies auto-fill defaults if no draft)

    WidgetsBinding.instance.addPostFrameCallback((_) async {
      final deviceId = await DeviceSession.id;
      DebugLogger.logEvent('SCREEN_ENTERED', 'profile_setup deviceId=$deviceId');
    });
  }

  void _handleUsernameFocusChange() {
    if (_usernameFocusNode.hasFocus && _usernameIsAutoGenerated) {
      _usernameController.selection = TextSelection(
        baseOffset: 0,
        extentOffset: _usernameController.text.length,
      );
    }
  }

  Timer? _debounce;
  void _onUsernameChanged() {
    // If the text no longer matches the auto-generated suggestion we filled
    // in, the user has genuinely started editing it — stop treating it as
    // "auto-generated" (select-all-on-focus should only apply to the
    // untouched suggestion, not to what the user typed themselves).
    if (_autoGeneratedUsername != null &&
        _usernameController.text != _autoGeneratedUsername) {
      _usernameIsAutoGenerated = false;
      _autoGeneratedUsername = null;
      _clearUsernameAutogenFlag();
    }

    _saveDraft(); // Fix #5: persist on every change, not just on background
    _debounce?.cancel();
    _debounce = Timer(const Duration(milliseconds: 800), () {
      if (!mounted) return;
      final username = _usernameController.text;
      setState(() {
        _usernameLength = username.length;
        _usernameError = _validateUsernameText(username);
      });
    });
    // Keep the character counter live even before the debounce fires.
    setState(() => _usernameLength = _usernameController.text.length);
  }

  // Fix #5: persist and restore draft state across app backgrounding / kills.
  // Keys are scoped by DeviceSession.id (no uid exists pre-auth), same
  // resolution this file already uses for its debug/analytics events.
  Future<String> _usernameKey() async =>
      '${_draftKeyPrefix}_username_${await DeviceSession.id}';
  Future<String> _genderKey() async =>
      '${_draftKeyPrefix}_gender_${await DeviceSession.id}';

  Future<void> _restoreDraft() async {
    final prefs = await SharedPreferences.getInstance();
    final draftUsername = prefs.getString(await _usernameKey());
    final draftGender = prefs.getString(await _genderKey());
    final draftUsernameWasAutogen =
        prefs.getBool(await _usernameAutogenKey()) ?? false;
    if (!mounted) return;

    final hasDraftUsername = draftUsername != null && draftUsername.isNotEmpty;
    final hasDraftGender = draftGender != null && _genders.contains(draftGender);

    // NEW: generate defaults up-front if nothing was saved, so we can apply
    // them inside the same setState below.
    final generatedUsername = hasDraftUsername ? null : _generateUsername();

    setState(() {
      if (hasDraftUsername) {
        _usernameController.text = draftUsername;
        _usernameLength = draftUsername.length;
        _usernameError = _validateUsernameText(draftUsername);
        if (draftUsernameWasAutogen) {
          // The user closed the app without ever editing the suggested
          // username — keep the select-all-on-focus behavior active.
          _autoGeneratedUsername = draftUsername;
          _usernameIsAutoGenerated = true;
        }
      } else if (generatedUsername != null) {
        // NEW: no saved draft at all — auto-fill a suggested username.
        // Set the tracking fields BEFORE assigning .text so that if the
        // assignment synchronously notifies _onUsernameChanged, the
        // content-based check there already sees them matching and does
        // not clear the auto-generated flag.
        _autoGeneratedUsername = generatedUsername;
        _usernameIsAutoGenerated = true;
        _usernameController.text = generatedUsername;
        _usernameLength = generatedUsername.length;
        _usernameError = null; // always valid by construction
      }

      if (hasDraftGender) {
        _selectedGender = draftGender;
      } else {
        // NEW: default to "Prefer not to say" rather than leaving gender
        // blank and required — removes a second hard blocker on this screen.
        _selectedGender = 'Prefer not to say';
      }

      _draftRestored = true;
    });

    if (!hasDraftUsername && generatedUsername != null) {
      DebugLogger.logEvent(
          'PROFILE_SETUP_AUTOFILL_APPLIED', 'username=$generatedUsername');
      await _saveDraft();
      await _setUsernameAutogenFlag(true);
    } else if (!hasDraftGender) {
      await _saveDraft();
    }
  }

  Future<void> _saveDraft() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(await _usernameKey(), _usernameController.text);
    if (_selectedGender != null) {
      await prefs.setString(await _genderKey(), _selectedGender!);
    }
  }

  Future<void> _setUsernameAutogenFlag(bool value) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(await _usernameAutogenKey(), value);
  }

  Future<void> _clearUsernameAutogenFlag() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.remove(await _usernameAutogenKey());
  }

  Future<void> _clearDraft() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.remove(await _usernameKey());
    await prefs.remove(await _genderKey());
    await prefs.remove(await _usernameAutogenKey());
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.paused ||
        state == AppLifecycleState.inactive) {
      _saveDraft(); // Fix #5: belt-and-suspenders save on backgrounding
    }
  }

  @override
  void dispose() {
    final deviceId = DeviceSession.idSync ?? 'anonymous';
    AnalyticsService.screenExit(
      screenName: 'profile_setup',
      uid: deviceId,
    );
    WidgetsBinding.instance.removeObserver(this);
    _debounce?.cancel();
    _usernameController.removeListener(_onUsernameChanged);
    _usernameFocusNode.removeListener(_handleUsernameFocusChange);
    _usernameFocusNode.dispose();
    _usernameController.dispose();
    super.dispose();
  }

  String? _validateUsernameText(String username) {
    if (username.isEmpty) return null;

    if (username.length < 3) {
      return "Username must be at least 3 characters";
    }

    if (username.length > 20) {
      return "Username must be 20 characters or fewer";
    }

    if (!RegExp(r'^[a-z0-9_.]+$').hasMatch(username)) {
      return "Only lowercase letters, numbers, . and _ allowed";
    }

    if (username.contains('..') ||
        username.contains('__') ||
        username.contains('._') ||
        username.contains('_.')) {
      return "Cannot have consecutive . or _ characters";
    }

    return null;
  }

  Future<void> completeProfile() async {
    setState(() => _submitAttempted = true);

    final usernameError = _validateUsernameText(_usernameController.text);
    final missingGender = _selectedGender == null;
    final missingUsername =
        usernameError != null || _usernameController.text.trim().isEmpty;

    if (missingUsername || missingGender) {
      setState(() => _usernameError = usernameError);
      final missing = <String>[];
      if (missingUsername) missing.add(usernameError ?? "a username");
      if (missingGender) missing.add("your gender");
      showSnackBar(context, "Please provide: ${missing.join(', ')}");
      return;
    }

    setState(() => _isLoading = true);

    final deviceId = DeviceSession.idSync ?? await DeviceSession.id;
    DebugLogger.logEvent(
        'PROFILE_SETUP_SUBMIT_STARTED', 'deviceId=$deviceId');

    final res = await AuthMethods().completeProfileSupabase(
      username: _usernameController.text.trim(),
      bio: "",
      file: null,
      dateOfBirth: widget.dateOfBirth,
      gender: _selectedGender!,
    );

    DebugLogger.logEvent(
        'PROFILE_SETUP_SUBMIT_RESULT', 'deviceId=$deviceId result=$res');

    if (res == "success") {
      await _clearDraft(); // Fix #5: don't resurrect a completed profile's draft
      widget.onComplete();

      if (mounted) {
        Navigator.pushAndRemoveUntil(
          context,
          MaterialPageRoute(
            builder: (context) => const ResponsiveLayout(
              mobileScreenLayout: MobileScreenLayout(),
            ),
          ),
          (route) => false,
        );
      }
    } else {
      if (mounted) showSnackBar(context, res);
    }

    if (mounted) setState(() => _isLoading = false);
  }

  bool get _isFormValid {
    return _validateUsernameText(_usernameController.text) == null &&
        _usernameController.text.trim().isNotEmpty &&
        _selectedGender != null;
  }

  @override
  Widget build(BuildContext context) {
    final showUsernameRequiredHint =
        _submitAttempted && _usernameController.text.trim().isEmpty;
    final showGenderRequiredHint = _submitAttempted && _selectedGender == null;

    return Scaffold(
      backgroundColor: const Color(0xFF121212),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 24.0),
          child: SingleChildScrollView(
            child: Column(
              children: [
                const SizedBox(height: 60),
                const Text(
                  'Profile Setup',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontWeight: FontWeight.w700,
                    fontFamily: 'Montserrat',
                    height: 1.3,
                  ),
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: 40),
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: const [
                        Text(
                          'Create your username',
                          style: TextStyle(
                            color: Color(0xFFd9d9d9),
                            fontSize: 14,
                            fontFamily: 'Inter',
                          ),
                        ),
                        SizedBox(width: 6),
                        Text(
                          '(required)',
                          style: TextStyle(
                            color: Color(0xFF8a8a8a),
                            fontSize: 12,
                            fontFamily: 'Inter',
                            fontStyle: FontStyle.italic,
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 8),
                    TextFieldInput(
                      hintText: 'username',
                      textInputType: TextInputType.text,
                      textEditingController: _usernameController,
                      // NEW: needed for select-all-on-focus. If
                      // TextFieldInput doesn't currently expose a focusNode
                      // param, add `FocusNode? focusNode` to its constructor
                      // and forward it to the underlying TextField — same
                      // situation as the inputFormatters param below.
                      focusNode: _usernameFocusNode,
                      fillColor: const Color(0xFF333333),
                      hintStyle: TextStyle(
                        color: Colors.grey[400],
                        fontFamily: 'Inter',
                      ),
                      inputFormatters: [_UsernameFormatter()],
                    ),
                    Padding(
                      padding: const EdgeInsets.only(top: 4.0),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          if (_usernameError != null)
                            Expanded(
                              child: Semantics(
                                liveRegion: true,
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  children: [
                                    const Icon(Icons.error_outline,
                                        color: Colors.red, size: 14),
                                    const SizedBox(width: 4),
                                    Flexible(
                                      child: Text(
                                        _usernameError!,
                                        style: const TextStyle(
                                          color: Colors.red,
                                          fontSize: 12,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            )
                          else if (showUsernameRequiredHint)
                            Expanded(
                              child: Semantics(
                                liveRegion: true,
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  children: const [
                                    Icon(Icons.error_outline,
                                        color: Colors.orangeAccent, size: 14),
                                    SizedBox(width: 4),
                                    Text(
                                      "Username is required",
                                      style: TextStyle(
                                        color: Colors.orangeAccent,
                                        fontSize: 12,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            )
                          else
                            const SizedBox.shrink(),
                          Text(
                            '$_usernameLength/20',
                            style: TextStyle(
                              color: _usernameLength > 20
                                  ? Colors.red
                                  : Colors.grey,
                              fontSize: 12,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 24),
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: const [
                        Text(
                          'Select your gender',
                          style: TextStyle(
                            color: Color(0xFFd9d9d9),
                            fontSize: 14,
                            fontFamily: 'Inter',
                          ),
                        ),
                        SizedBox(width: 6),
                        Text(
                          '(required)',
                          style: TextStyle(
                            color: Color(0xFF8a8a8a),
                            fontSize: 12,
                            fontFamily: 'Inter',
                            fontStyle: FontStyle.italic,
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 8),
                    Container(
                      decoration: BoxDecoration(
                        color: const Color(0xFF333333),
                        borderRadius: BorderRadius.circular(12),
                        border: showGenderRequiredHint
                            ? Border.all(color: Colors.orangeAccent, width: 1)
                            : null,
                      ),
                      child: Padding(
                        padding: const EdgeInsets.symmetric(horizontal: 12),
                        child: DropdownButtonFormField<String>(
                          dropdownColor: const Color(0xFF333333),
                          value: _selectedGender,
                          decoration: const InputDecoration(
                            border: InputBorder.none,
                          ),
                          items: _genders.map((String value) {
                            return DropdownMenuItem<String>(
                              value: value,
                              child: Text(
                                value,
                                style: const TextStyle(
                                  color: Color(0xFFd9d9d9),
                                  fontFamily: 'Inter',
                                ),
                              ),
                            );
                          }).toList(),
                          onChanged: (value) {
                            setState(() => _selectedGender = value);
                            _saveDraft(); // Fix #5
                          },
                          icon: const Icon(Icons.arrow_drop_down,
                              color: Color(0xFFd9d9d9)),
                          style: const TextStyle(
                            color: Color(0xFFd9d9d9),
                            fontFamily: 'Inter',
                          ),
                          hint: const Text(
                            'Choose gender',
                            style: TextStyle(
                              color: Color(0xFFd9d9d9),
                              fontFamily: 'Inter',
                            ),
                          ),
                        ),
                      ),
                    ),
                    if (showGenderRequiredHint)
                      Padding(
                        padding: const EdgeInsets.only(top: 4.0),
                        child: Semantics(
                          liveRegion: true,
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            children: const [
                              Icon(Icons.error_outline,
                                  color: Colors.orangeAccent, size: 14),
                              SizedBox(width: 4),
                              Text(
                                "Gender is required",
                                style: TextStyle(
                                  color: Colors.orangeAccent,
                                  fontSize: 12,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                  ],
                ),
                const SizedBox(height: 40),
                ElevatedButton(
                  style: ElevatedButton.styleFrom(
                    backgroundColor: _isFormValid
                        ? const Color(0xFF333333)
                        : const Color(0xFF2a2a2a),
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                    minimumSize: const Size(double.infinity, 50),
                  ),
                  onPressed: _isLoading ? null : completeProfile,
                  child: _isLoading
                      ? const CircularProgressIndicator(
                          valueColor:
                              AlwaysStoppedAnimation<Color>(Colors.white),
                        )
                      : Text(
                          'Complete Profile',
                          style: TextStyle(
                            color:
                                _isFormValid ? Colors.white : Colors.grey[400],
                            fontSize: 16,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'Inter',
                          ),
                        ),
                ),
                const SizedBox(height: 20),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
